const productData = [
  {
    id: 1,
    hinh: require("@/assets/img/sale-img/hoahongmixtrang.png"),
    ten: "Bó hoa hồng mix trắng",
    gia: 700000,
    phantramgiamgia: 0,
    luotmua: 9,
    mau: "Màu trắng",
    hinhdang: "Bó hoa",
    chude: ["Hoa sinh nhật, ", "Hoa tốt nghiệp, ", "Hoa 20/11, ", "Hoa 8/3 "],
    rate: 4.5,
    quantity: 13,
    description:
      "Bó hoa hồng trắng tinh khôi, tượng trưng cho sự thanh lịch và thuần khiết.",
    detailDescription:
      "Bó hoa hồng mix trắng với những bông hoa hồng tươi, màu trắng tinh khôi, được bó gọn gàng và tinh tế. Phù hợp để tặng vào các dịp đặc biệt như sinh nhật, tốt nghiệp, hay các ngày lễ 8/3, 20/11, mang đến sự tinh tế và trang nhã.",
  },
  {
    id: 2,
    hinh: require("@/assets/img/sale-img/hoakhomini.png"),
    ten: "Bó hoa khô mini",
    gia: 300000,
    phantramgiamgia: 0.2,
    luotmua: 2,
    mau: "Màu trắng",
    hinhdang: "Bó hoa",
    chude: "Hoa tốt nghiệp",
    rate: 4.0,
    quantity: 10,
    description:
      "Bó hoa khô mini xinh xắn, thích hợp cho các dịp lễ và tốt nghiệp.",
    detailDescription:
      "Bó hoa khô mini với tông màu trắng chủ đạo, kết hợp từ nhiều loại hoa khô khác nhau, tạo nên vẻ đẹp mộc mạc và sang trọng. Thích hợp để tặng trong các dịp lễ như tốt nghiệp, tạo dấu ấn khó quên và bền lâu.",
  },
  {
    id: 3,
    hinh: require("@/assets/img/sale-img/chauhoahuongduong.png"),
    ten: "Lẳng hoa hướng dương",
    gia: 900000,
    phantramgiamgia: 0.3,
    luotmua: 3,
    mau: "Màu vàng",
    hinhdang: "Lẳng hoa",
    chude: ["Hoa sinh nhật, ", "Hoa 8/3, ", "Hoa 20/11 "],
    rate: 4.8,
    quantity: 15,
    description:
      "Lẳng hoa hướng dương rực rỡ, mang thông điệp vui tươi và tràn đầy năng lượng.",
    detailDescription:
      "Lẳng hoa hướng dương được thiết kế với những bông hoa vàng rực rỡ, nổi bật và thu hút. Thích hợp để tặng vào các dịp sinh nhật, lễ 8/3, hay 20/11, gửi gắm thông điệp về niềm vui, sự lạc quan và năng lượng tích cực.",
  },
  {
    id: 4,
    hinh: require("@/assets/img/sale-img/hoahongmixhoadongtien.png"),
    ten: "Lẳng hoa hồng đồng tiền",
    gia: 600000,
    phantramgiamgia: 0.4,
    luotmua: 2,
    mau: "Mix màu",
    hinhdang: "Lẳng hoa",
    chude: ["Hoa sinh nhật, ", "Hoa 8/3, ", "Hoa 20/11, ", "Hoa tốt nghiệp"],
    rate: 4.2,
    quantity: 12,
    description:
      "Lẳng hoa hồng và hoa đồng tiền đa sắc, phù hợp cho mọi dịp lễ.",
    detailDescription:
      "Sự kết hợp hài hòa giữa hoa hồng và hoa đồng tiền trong lẳng hoa này tạo nên một tổng thể sinh động và cuốn hút. Với màu sắc đa dạng và sự tinh tế trong từng chi tiết, sản phẩm này là lựa chọn hoàn hảo cho các dịp đặc biệt như sinh nhật, tốt nghiệp, hay các ngày lễ tôn vinh phái đẹp.",
  },
  {
    id: 5,
    hinh: require("@/assets/img/sale-img/giahoahong.png"),
    ten: "Vòng hoa hồng",
    gia: 900000,
    phantramgiamgia: 0.5,
    luotmua: 5,
    mau: "Mix màu",
    hinhdang: "Vòng hoa",
    chude: "Hoa khai trương",
    rate: 4.7,
    quantity: 11,
    description:
      "Vòng hoa hồng mix màu, mang lại sự sang trọng cho dịp khai trương.",
    detailDescription:
      "Vòng hoa hồng được thiết kế từ các bông hoa hồng đa màu sắc, tượng trưng cho sự may mắn và thành công. Đây là lựa chọn tuyệt vời để trang trí hoặc làm quà tặng trong dịp khai trương, mang đến thông điệp chúc mừng và thịnh vượng.",
  },
  {
    id: 6,
    hinh: require("@/assets/img/sale-img/bohoadongtien.png"),
    ten: "Bó hoa đồng tiền",
    gia: 200000,
    phantramgiamgia: 0.6,
    luotmua: 3,
    mau: "Màu đỏ",
    hinhdang: "Bó hoa",
    chude: ["Hoa sinh nhật, ", "Hoa 8/3, ", "Hoa 20/11, ", "Hoa tốt nghiệp"],
    rate: 4.1,
    quantity: 16,
    description:
      "Bó hoa đồng tiền đỏ nổi bật, thể hiện sự nhiệt huyết và niềm vui.",
    detailDescription:
      "Bó hoa đồng tiền màu đỏ được gói cẩn thận và tinh tế, mang lại vẻ đẹp rực rỡ và cuốn hút. Phù hợp để tặng vào các dịp lễ, sinh nhật, hay ngày tôn vinh giáo viên, thể hiện sự quý mến và trân trọng.",
  },
  {
    id: 7,
    hinh: require("@/assets/img/sale-img/bohoahongmixnho.png"),
    ten: "Bó hoa hồng mix đỏ",
    gia: 780000,
    phantramgiamgia: 0,
    luotmua: 7,
    mau: "Mix màu",
    hinhdang: "Bó hoa",
    chude: ["Hoa sinh nhật, ", "Hoa 8/3, ", "Hoa 20/11, ", "Hoa tốt nghiệp"],
    rate: 4.6,
    quantity: 17,
    description:
      "Bó hoa hồng mix màu đỏ đầy cảm xúc, dành cho những dịp đặc biệt.",
    detailDescription:
      "Bó hoa hồng được phối hợp từ các bông hoa đỏ thắm và các màu sắc khác, tạo nên sự hài hòa và cuốn hút. Thích hợp để làm quà tặng vào các dịp lễ như sinh nhật, 8/3, hoặc ngày nhà giáo 20/11, mang lại sự chân thành và ấm áp.",
  },
  {
    id: 8,
    hinh: require("@/assets/img/sale-img/bohoalytrang.png"),
    ten: "Bó hoa ly trắng",
    gia: 500000,
    phantramgiamgia: 0,
    luotmua: 8,
    mau: "Màu trắng",
    hinhdang: "Bó hoa",
    chude: ["Hoa sinh nhật, ", "Hoa 8/3, ", "Hoa 20/11, ", "Hoa tốt nghiệp"],
    rate: 4.4,
    quantity: 18,
    description:
      "Bó hoa ly trắng tinh khôi, mang lại sự thanh thoát và sang trọng.",
    detailDescription:
      "Bó hoa ly trắng với những cánh hoa mềm mại và thanh nhã, tượng trưng cho sự tinh khiết và sang trọng. Đây là lựa chọn tuyệt vời cho các dịp đặc biệt, như sinh nhật, 8/3, hoặc tốt nghiệp, giúp tạo nên không gian thanh lịch và tinh tế.",
  },
  {
    id: 9,
    hinh: require("@/assets/img/sale-img/giahoavang.png"),
    ten: "Vòng hoa vàng",
    gia: 800000,
    phantramgiamgia: 0,
    luotmua: 9,
    mau: "Màu vàng",
    hinhdang: "Vòng hoa",
    chude: "Hoa khai trương",
    rate: 4.9,
    quantity: 19,
    description:
      "Vòng hoa vàng rực rỡ, biểu tượng của sự thành công và thịnh vượng.",
    detailDescription:
      "Với các bông hoa màu vàng rực rỡ, vòng hoa này mang đến vẻ đẹp nổi bật và đầy năng lượng. Đây là món quà lý tưởng cho dịp khai trương, tượng trưng cho sự thịnh vượng và thành công trong công việc.",
  },
  {
    id: 10,
    hinh: require("@/assets/img/sale-img/langhoahduong.png"),
    ten: "Lẳng hoa hướng dương",
    gia: 500000,
    phantramgiamgia: 0,
    luotmua: 7,
    mau: "Màu vàng",
    hinhdang: "Lẳng hoa",
    chude: ["Hoa sinh nhật, ", "Hoa 8/3, ", "Hoa 20/11, ", "Hoa tốt nghiệp"],
    rate: 4.3,
    quantity: 21,
    description:
      "Lẳng hoa hướng dương tươi sáng, mang đến sự lạc quan và vui vẻ.",
    detailDescription:
      "Lẳng hoa được thiết kế với những bông hướng dương vàng rực, mang lại cảm giác tươi sáng và vui vẻ. Phù hợp làm quà tặng hoặc trang trí trong các dịp khai trương, lẳng hoa này gửi gắm thông điệp về sự phát triển và thành công.",
  },
  {
    id: 11,
    hinh: require("@/assets/img/sale-img/hoahongxanh.png"),
    ten: "Hoa hồng xanh",
    gia: 500000,
    phantramgiamgia: 0,
    luotmua: 2,
    mau: "Màu xanh",
    hinhdang: "Bó hoa",
    chude: ["Hoa sinh nhật, ", "Hoa 8/3, ", "Hoa 20/11, ", "Hoa tốt nghiệp"],
    rate: 4.0,
    quantity: 23,
    description: "Bó hoa hồng xanh độc đáo, thể hiện sự tươi mới và sáng tạo.",
    detailDescription:
      "Bó hoa hồng xanh với màu sắc lạ mắt và cuốn hút, mang lại cảm giác tươi mới và đầy sáng tạo. Sản phẩm này là lựa chọn thú vị cho những dịp đặc biệt, tạo nên điểm nhấn độc đáo và khác biệt.",
  },
  {
    id: 12,
    hinh: require("@/assets/img/sale-img/hoahonggiayden.png"),
    ten: "Hoa hồng mix màu",
    gia: 1000000,
    phantramgiamgia: 0,
    luotmua: 7,
    mau: "Mix màu",
    hinhdang: "Lẳng hoa",
    chude: ["Hoa sinh nhật, ", "Hoa 8/3, ", "Hoa 20/11, ", "Hoa tốt nghiệp"],
    rate: 4.5,
    quantity: 20,
    description:
      "Lẳng hoa hồng mix màu đầy màu sắc, tạo nên không gian tươi mới và ấm áp.",
    detailDescription:
      "Lẳng hoa hồng được kết hợp từ nhiều màu sắc khác nhau, mang lại sự hài hòa và cuốn hút. Đây là lựa chọn tuyệt vời cho những dịp đặc biệt như sinh nhật hay các ngày lễ quan trọng, thể hiện sự yêu thương và tinh tế.",
  },
];

export default productData;
